- name: Version Badge
  uses: schneegans/dynamic-badges-action@v1.1.0
  with:
    auth: ${{ secrets.GIST_SECRET }}
    gistID: c630ad7d59667921444cdae94e0c0520
    filename: version.json
    label: beta
    message: v1.0-beta1
    color: orange
